#!/bin/bash
nice tail -n 20000 "/var/opt/intershop/eserver2/log/httpd/access-`date +%Y%m%d`-0000.log"| grep "`date --date="1 min ago" +"%d/%b/%Y:%H:%M"`"|egrep -v "127.0.0.1|::1|^10.47.5.|CloudFront" |cut -d' ' -f1 | sort -n | uniq -c |sort -n |tail -n 20 |awk '{printf("%-10s %s - ",$1 , $2) ; system("geoiplookup \"" $2 "\"")}'
